Documents/rejob_2016/config/routes.rb
Rails.application.routes.draw do
  get 'login/mypage'

  get 'sessions/login'

  get 'sessions/mypage'

  get 'sessions/sighnup'

  get 'login/edit'

  get 'admin_top/do'

  get 'admin_top/user'

  get 'jobs' ,to:"jobs#index"

  get 'job', to:"jobs#show"

  get 'entry' ,to:"jobs#entry"

  get 'jobs_job_detail' , to:"jobs#job_detail"

  get 'top/top_page'

  get 'jobs/area'

  get 'login', to:"login#index"

  get 'admin_top/do', to:"admin_top#do"

  get 'admin_top/user', to:"admin_top#user"

  get 'admin_new', to:"admin_top#new"

  get 'admin_destroy/:id', to:"admin_top#destroy"

  post 'admin_new', to:"admin_top#create"

  get 'sighnup', to:"sighnup#index"

  post 'sighnup', to:"sighnup#create"

  get 'login_through' ,to:"login#login_through"

  post 'sessions' ,to:"sessions#login"

  get 'login_check' ,to:"login#create"

  get 'mypage' ,to:"sessions#mypage"

  resources:edit

end

Documents/rejob_2016/app/models/area.rb
class Area < ActiveRecord::Base
end

Documents/rejob_2016/app/models/job.rb
class Job < ActiveRecord::Base
end

Documents/rejob_2016/app/models/job_type.rb
class JobType < ActiveRecord::Base
end

Documents/rejob_2016/app/models/post.rb
class Post < ActiveRecord::Base
end

Documents/rejob_2016/app/models/title.rb
class Area < ActiveRecord::Base
end

Documents/rejob_2016/app/models/user.rb
class User < ActiveRecord::Base
end

Documents/rejob_2016/app/models/user_job.rb
class UserJob < ActiveRecord::Base
end

Documents/rejob_2016/app/controllers/admin_top_controller.rb
class AdminTopController < ApplicationController
  def do
    @jobs = Job.all
    # @entry = UserJob.where(job_id: params[:id])
    @entry = UserJob.where(job_id: Job.all)
  end

  def index

    @edit = edit_page
  end

  def user
  end

  def new
    @job = Job.new
  end

  def create
    params[:job][:area_id] = params[:job][:area_id].to_i
    @job = Job.new(job_params)
    if @job.save
      redirect_to admin_top_do_path
    else
      render 'admin_new'
    end
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy
    redirect_to admin_top_do_path
  end
end

private

 def job_params
   params[:job].permit(:title,:detail,:area_id)
 end

Documents/rejob_2016/app/controllers/edit_controller.rb
class EditController < ApplicationController
  def index
    @jobs = Job.all
  end

  def show
    @job = Job.find(params[:id])
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)
    if @job.save
      redirect_to jobs_path
    else
      render 'new'
    end
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])
    if @job.update(job_params)
      redirect_to admin_top_do_path
    else
      render 'edit'
    end
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy
    redirect_to :jobs_path
  end
end

private

def job_params
  params[:job].permit(:title,:detail)
end

Documents/rejob_2016/app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def new
    @job = Job.new
  end

  def index
    if params[:area_id] == nil
      @jobs = Job.all
    else
      @jobs = Job.where(area_id: params[:area_id])
    end
  end

  def area
  end

  def show

    id = params[:id]
    @job = Job.find(id)

  end

  def show
    @job = Job.find(params[:id])
  end

  def entry # 応募して、応募した情報を取得する
    if session[:user_id].present?
      @user = User.find(session[:user_id])
      @entry = UserJob.new(job_id: params[:id],user_id: session[:user_id])
      @entry.save
      redirect_to'/login/mypage'

    else
       flash[:danger] = "登録できませんでした"
       redirect_to '/login'
    end
  end
end

Documents/rejob_2016/app/controllers/login_controller.rb
class LoginController < ApplicationController

  def index
  end

  def create
  # @userName = User.find_by(mail: params[:userId])

  user = User.find_by(mail: params[:user_id])
  if user && user.password == params[:password]
   session[:user_id] = user.id
   flash[:notice] = "こんにちは" + user.name + "さん"
   redirect_to "/login/mypage"
  else
  flash[:danger] = "ログインできませんでした。"
   redirect_to "/login"
  end
  end

  def mypage
  @entry = UserJob.where(user_id: session[:user_id])
  @job = Job.where(id: @entry.pluck(:job_id))
  @user = User.find_by(id: params[:id])

  # if session[:user_id] == params[:id].to_i
  # else
  # redirect_to "/login"
  # end
  end
end

Documents/rejob_2016/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def login
  end

  def mypage
  end

  def sighnup
  end
  def login_through
    redirec_to "top_top_page_path"
  end
end

Documents/rejob_2016/app/controllers/sighnup_controller.rb
class SighnupController < ApplicationController
  def index
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to top_top_page_path
    else
    end
  end

end

private

 def user_params
     params.permit(:name,:mail,:password)
 end

Documents/rejob_2016/app/controllers/top_controller.rb
class TopController < ApplicationController
  def top_page
  end
end

Documents/rejob_2016/app/helpers/admin_top_helper.rb
module AdminTopHelper
end

Documents/rejob_2016/app/helpers/application_helper.rb
module ApplicationHelper
end

Documents/rejob_2016/app/helpers/edit_helper.rb
module EditHelper
end

Documents/rejob_2016/app/helpers/joblist_helper.rb
module JoblistHelper
end

Documents/rejob_2016/app/helpers/jobs_helper.rb
module JobsHelper
end

Documents/rejob_2016/app/helpers/login_helper.rb
module LoginHelper
end

Documents/rejob_2016/app/helpers/sessions_helper.rb
module SessionsHelper
end

Documents/rejob_2016/app/helpers/top_helper.rb
module TopHelper
end

Documents/rejob_2016/app/views/admin_top/do.html.erb
<h3>管理画面 </h3>

<p>Find me in app/views/admin_top/do.html.erb</p>


<h2 class="heading1-pt1">
  求人一覧
  </h2>


 <br>

   <a href="/admin_new">
     <button type="new">新規作成</button>
   </a><br><br>


          <table border="1" class="table table-bordered table-hover table-striped" text-align="center">
          <thead><tr>
            <th style="width:5%">求人ID</th>
            <th style="width:5%">エリア</th>
            <th style="width:20%">タイトル</th>
            <th style="width:40%">説明文</th>
            <th style="width:15%">作成時刻</th>
            <th style="width:7%">応募数</th>
            <th style="width:7%" class="text-center">編集</th></tr>
          </thead>



          <% Job.all.each do |job| %>
           <% Job.order("job_id") %>
           <tr class="link">
               <td><%= job.id %></a></td>
               <td><%= Area.find(job.area_id).area %></a></td>
               <td><a href="/job/<%= job.id %>"><%= job.title %></a></td>
               <td><%= job.detail%></td>
               <td><%= job.created_at%></td>
               <td><%= UserJob.where(job_id: job.id).count %></td>
               <form method="get" action="http://localhost:3000/login/edit">
                 <td class="text-center">
                 <div class="button-margin" style="margin:0 auto" align="center">
                  <a class="btn btn-xs btn-warning" name="edit" href="/edit/<%= job.id %>/edit">Edit</a>
                </div>
                 </td>
            </tr>
          </tbody>

   <% end %>

<ul>

<%= link_to '戻っちゃうよ',top_top_page_path %>

</div>

</ul>

Documents/rejob_2016/app/views/admin_top/new.html.erb
<%= stylesheet_link_tag "inside/stories", :media => "all" %>
<h2 class="heading1-pt1">
  管理画面＿新規作成ページ</h2>

  <%= form_for @job, :url => {:action => 'create'} do |f| %>
  <div class="field">
   <%= f.label :title, "タイトル" %>
   <%= f.text_field :title %>
 </div>

 <div class="field">
   <%= f.label :detail, "詳細" %>
   <%= f.text_field :detail %>
 </div>

<div class="field">
  <%= f.label :area_id, "エリア" %>
  <%= f.collection_select :area_id, Area.all, :id, :area, :include_blank => true %>
</div>


 <div class="actions">
   <%= f.submit "送信する" %>
 </div>
<% end %>

Documents/rejob_2016/app/views/admin_top/user.html.erb
<h1>AdminTop#user</h1>
<p>Find me in app/views/admin_top/user.html.erb</p>

Documents/rejob_2016/app/views/edit/edit.html.erb
  <link href="/stylesheets/inside/stories.css" media="all" rel="stylesheet">
  <h2 class="heading1-pt1">
       管理画面＿求人編集ページ</h2>



   <%= form_for @job , url: {controller: "edit", action: "update"} do |f| %>

     <p>
       <%= f.label :"タイトル" %><br>
       <%= f.text_field :title, :size =>"100" %>
     </p>
     <p>
       <%= f.label :"詳細"%><br>
       <%= f.text_area :detail , :size =>"100x10" %>
     </p>
     <p>
       <%= f.submit "編集" %>
       <a class="btn btn-xs btn-warning" name="edit" href="/admin_destroy/<%= params[:id] %>">destroy</a>
     </p>



   <% end %>


　　　　
　　　　　<%= link_to '戻っちゃうよ',admin_top_do_path %>

Documents/rejob_2016/app/views/top/top_page.html.erb
<!DOCTYPE HTML>

 <div align="center" style="width:50%: margin:0 auto;">
   <br><br>
    <a class="header-middle__logo" href="/top/top_page" align="center"><%= image_tag 'logo_header.png' %></a>
    <br><br>
    <div style="font-size:22px">

     <br>

     <br>
     <p><%= link_to '・案件一覧',jobs_path %></p>
     <br>
     <p><%= link_to '・詳細',jobs_job_detail_path %></p>
     <br>
     <p><%= link_to '・ログイン',login_path%></p>
     <br>
     <br>
    </div>
 </div>
 <p>Find me in app/views/top/top_page.html.erb</p>